table fact_cargo_movements
	lineageTag: 1c984a18-2b6e-455a-8b24-db258ca8c84f

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: db86480e-f667-40a8-85d7-bb071a83071c
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column vessel_key
		dataType: string
		lineageTag: 929e6be2-d988-4974-84af-b67d0305e648
		summarizeBy: none
		sourceColumn: vessel_key

		annotation SummarizationSetBy = Automatic

	column terminal_id
		dataType: int64
		formatString: 0
		lineageTag: 39000a8e-bb5a-4641-8e08-6b0f21e6b2c4
		summarizeBy: none
		sourceColumn: terminal_id

		annotation SummarizationSetBy = Automatic

	column container_count
		dataType: int64
		formatString: 0
		lineageTag: 4ba2c74f-f7c3-4a45-8baa-aee3228a2675
		summarizeBy: sum
		sourceColumn: container_count

		annotation SummarizationSetBy = Automatic

	column 'move_duration (hrs)'
		dataType: double
		formatString: 0
		lineageTag: 0d3b60c0-1333-4ada-a1b6-4a4ee9d0eead
		summarizeBy: sum
		sourceColumn: move_duration (hrs)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'move_duration (days)' = DIVIDE(fact_cargo_movements[move_duration (hrs)],24,0)
		formatString: 0.00
		lineageTag: c532063b-f3be-4d85-aa7a-ec5aac0fabb2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column movement_id
		dataType: int64
		formatString: 0
		lineageTag: 755b9ae3-bb7d-40e2-a0dd-c0089d9cd9b7
		summarizeBy: none
		sourceColumn: movement_id

		annotation SummarizationSetBy = User

	column 'Duration Flag' = ```
			
			VAR ActualDuration = fact_cargo_movements[move_duration (days)]
			
			VAR Benchmark = 
			    RELATED(dim_vessel[Avg Move Duration (Category Benchmark)])
			
			VAR VariancePct = DIVIDE(ActualDuration - Benchmark, Benchmark)
			
			RETURN
			SWITCH(
			    TRUE(),
			    VariancePct <= -0.90,   "Invalid",
			    VariancePct <= -0.50,   "Fast",
			    VariancePct <= 0.0,     "On Time",
			    VariancePct <= 0.20,    " Delayed",
			    VariancePct <= 0.50,    "Late",
			                            "Critical"
			)
			```
		lineageTag: ea7a2508-3891-4129-91de-429cd7e3e5a3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'capacity flag' =
			
			VAR contaiiner_count = fact_cargo_movements[container_count]
			
			VAR vessel_capacity = RELATED(dim_vessel[vessel capacity])
			
			VAR VariancePct = DIVIDE(contaiiner_count - vessel_capacity, vessel_capacity)
			
			RETURN
			SWITCH(
			    TRUE(),
			    VariancePct <= -1.00,   "Empty",
			    VariancePct <= -0.50,   "Light",
			    VariancePct <= 0.00,    "Optimal",
			    VariancePct <= 0.20,    "Strained",
			    VariancePct <= 0.50,    "Over",
			                            "Critical"
			)
		lineageTag: 90743430-ccd8-4ddb-8058-096297276167
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Performance Flag' =
			
			VAR CapacityFlag = fact_cargo_movements[capacity flag]
			VAR DurationFlag = fact_cargo_movements[Duration Flag]
			RETURN
			SWITCH(
			    TRUE(),
			
			    -- Data quality rows (Invalid Duration - any capacity)
			    DurationFlag = "Invalid",    "Unverified",
			
			    -- Empty vessel rows
			    CapacityFlag = "Empty"    && DurationFlag = "Fast",     "Repositioning",
			    CapacityFlag = "Empty"    && DurationFlag = "On Time", "Repositioning",
			    CapacityFlag = "Empty"    && DurationFlag = "Delayed",  "Lagging",
			    CapacityFlag = "Empty"    && DurationFlag = "Late",     "Lagging",
			    CapacityFlag = "Empty"    && DurationFlag = "Critical", "Critical",
			
			    -- Light capacity rows
			    CapacityFlag = "Light"    && DurationFlag = "Fast",     "Peak",
			    CapacityFlag = "Light"    && DurationFlag = "On Time",  "Efficient",
			    CapacityFlag = "Light"    && DurationFlag = "Delayed",  "Lagging",
			    CapacityFlag = "Light"    && DurationFlag = "Late",     "At Risk",
			    CapacityFlag = "Light"    && DurationFlag = "Critical",  "Critical",
			
			    -- Optimal capacity
			    CapacityFlag = "Optimal"  && DurationFlag = "Fast",        "Peak",
			    CapacityFlag = "Optimal"  && DurationFlag = "On Time",         "Peak",
			    CapacityFlag = "Optimal"  && DurationFlag = "Delayed",      "Efficient",
			    CapacityFlag = "Optimal"  && DurationFlag = "Late",         "Lagging",
			    CapacityFlag = "Optimal"  && DurationFlag = "Critical",        "Critical",
			
			    -- Strained capacity
			    CapacityFlag = "Strained" && DurationFlag = "Fast",     "Efficient",
			    CapacityFlag = "Strained" && DurationFlag = "On Time",     "Efficient",
			    CapacityFlag = "Strained" && DurationFlag = "Delayed",      "Lagging",
			    CapacityFlag = "Strained" && DurationFlag = "Late",     "At Risk",
			    CapacityFlag = "Strained" && DurationFlag = "Critical",    "Critical",
			
			    -- Overloaded capacity
			    CapacityFlag = "Over"     && DurationFlag = "Fast",     "At Risk",
			    CapacityFlag = "Over"     && DurationFlag = "On Time",     "Overloaded",
			    CapacityFlag = "Over"     && DurationFlag = "Delayed",      "At Risk",
			    CapacityFlag = "Over"     && DurationFlag = "Late",     "Critical",
			    CapacityFlag = "Over"     && DurationFlag = "Critical",        " Failed",
			
			    -- Critical overload
			    CapacityFlag = "Critical" && DurationFlag = "Fast",        "At Risk",
			    CapacityFlag = "Critical" && DurationFlag = "On Time",        "Critical",
			    CapacityFlag = "Critical" && DurationFlag = "Delayed",     "Critical",
			    CapacityFlag = "Critical" && DurationFlag = "Late",        " Failed",
			    CapacityFlag = "Critical" && DurationFlag = "Critical",       " Failed",
			
			    "Unverified"
			)
		lineageTag: e97f17cd-2ba9-4346-968c-45ea0eadfdf3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Performance Flag SVG' = ```
			
			VAR _Status = fact_cargo_movements[Performance Flag]
			
			-- Assign Hex Colors based on Status
			VAR _BGColor = 
			    SWITCH( _Status,
			       "Peak", "#27AE60",          -- Strong Green
			        "Efficient", "#2ECC71",     -- Bright Emerald
			        "Repositioning", "#3498DB",  -- Bright Blue
			        "Lagging", "#F1C40F",          -- Vivid Yellow
			        "Overloaded", "#E67E22",    -- Carrot Orange
			        "At Risk", "#D35400",       -- Pumpkin Orange
			        "Critical", "#E74C3C",      -- Soft Red
			        "Failed", "#C0392B",        -- Deep Red
			        "Unverified", "#BDC3C7",    -- Silver/Grey
			        "#ECF0F1"                   -- Very Light Grey (Default)
			    )
			
			-- SVG Parameters
			VAR _Width = 100
			VAR _Height = 35
			VAR _Radius = 5
			VAR _FontSize = 12
			VAR _TextColor = "#444040" -- Dark text for readability
			
			RETURN
			"data:image/svg+xml;utf8," & 
			"<svg xmlns='http://www.w3.org/2000/svg' width='" & _Width & "' height='" & _Height & "'>" &
			  "<rect x='5' y='5' rx='" & _Radius & "' ry='" & _Radius & "' width='" & (_Width - 10) & "' height='" & (_Height - 10) & "' fill='" & _BGColor & "' stroke='rgba(0,0,0,0.1)' stroke-width='1' />" &
			  "<text x='50%25' y='53%25' dominant-baseline='middle' text-anchor='middle' font-family='Segoe UI, Arial' font-size='" & _FontSize & "' font-weight='600' fill='" & _TextColor & "'>" & 
			    _Status & 
			  "</text>" &
			"</svg>"
			```
		lineageTag: dc825718-9459-4af0-b665-92b1eca7a87b
		dataCategory: ImageUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fact_cargo_movements = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("\\Mac\Home\Downloads\DataDNA Dataset Challenge - International Maritime Logistics  Terminal Efficiency\Data\International Maritime Logistics Terminal Efficiency.xlsx"), null, true),
				    fact_cargo_movements_Sheet = Source{[Item="fact_cargo_movements",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(fact_cargo_movements_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"movement_id", Int64.Type}, {"date_id", type date}, {"vessel_key", type text}, {"terminal_id", Int64.Type}, {"container_count", Int64.Type}, {"move_duration", type number}, {"start_longitude", type number}, {"start_latitude", type number}, {"end_longitude", type number}, {"end_latitude", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"move_duration", "move_duration (hrs)"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"movement_id", "date_id", "vessel_key", "terminal_id", "container_count", "move_duration (hrs)"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Other Columns",{{"date_id", Order.Ascending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Index",{"movement_id"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"Index", "date_id", "vessel_key", "terminal_id", "container_count", "move_duration (hrs)"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"Index", "movement_id"}, {"date_id", "date"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

